import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Hero from '../components/Hero'
import About from '../components/About'
import WorkExperience from '../components/WorkExperience'
import Education from '../components/Education'
import Skills from '../components/Skills'
import ContactMe from '../components/ContactMe'
import Footer from '../components/Footer'
import DarkModeProvider from '../components/DarkModeContext';

const Home: NextPage = () => {
  return (
    <DarkModeProvider>
      <div className="dark:bg-[rgb(36,36,36)] dark:text-white bg-[#FEFEFE] text-black h-screen snap-y snap-mandatory overflow-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-gray-400/20 scrollbar-thumb-[#7a28cb]/80">
        <Head>
          <title>Ruchit&#39;s portfolio</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <section id='hero' className='snap-start'>
          <Hero />
        </section>

        <section id='about' className='snap-start'>
          <About />
        </section>

        <section id='education' className='snap-start'>
          <Education />
        </section>

        <section id='experience' className='snap-start'>
          <WorkExperience />
        </section>

        <section id='skills' className='snap-start'>
          <Skills />
        </section>

        {/* <section id='projects' className='snap-start'>
          <Projects />
        </section> */}

        <section id='contact' className='snap-start'>
          <ContactMe />
        </section>

        <Footer />

      </div>
    </DarkModeProvider>

  )
}

export default Home
